<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OneTable.Gateway</RootNamespace>
    <AssemblyName>OneTable.Gateway</AssemblyName>
  </PropertyGroup>
</Project>
